[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
tokio = { version = "1.43.0", features = ["full"] }

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
